# Generated by Django 3.2.6 on 2022-02-13 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chickenpox', models.BooleanField(default=False)),
                ('dt', models.BooleanField(default=False)),
                ('dtap', models.BooleanField(default=False)),
                ('td', models.BooleanField(default=False)),
                ('tdap', models.BooleanField(default=False)),
                ('flu', models.BooleanField(default=False)),
                ('hav', models.BooleanField(default=False)),
                ('hbv', models.BooleanField(default=False)),
                ('hib', models.BooleanField(default=False)),
                ('hpv', models.BooleanField(default=False)),
                ('mmr', models.BooleanField(default=False)),
                ('meningococcal', models.BooleanField(default=False)),
                ('pcv13', models.BooleanField(default=False)),
                ('ppsv23', models.BooleanField(default=False)),
                ('ipv', models.BooleanField(default=False)),
                ('opv', models.BooleanField(default=False)),
                ('rotavirus', models.BooleanField(default=False)),
                ('rzv', models.BooleanField(default=False)),
                ('bcg', models.BooleanField(default=False)),
                ('tyfoidFever', models.BooleanField(default=False)),
                ('yellowFever', models.BooleanField(default=False)),
                ('covid19', models.BooleanField(default=False)),
                ('chickenpoxD', models.DateField(null=True)),
                ('dtD', models.DateField(null=True)),
                ('dtapD', models.DateField(null=True)),
                ('tdD', models.DateField(null=True)),
                ('tdapD', models.DateField(null=True)),
                ('fluD', models.DateField(null=True)),
                ('havD', models.DateField(null=True)),
                ('hbvD', models.DateField(null=True)),
                ('hibD', models.DateField(null=True)),
                ('hpvD', models.DateField(null=True)),
                ('mmrD', models.DateField(null=True)),
                ('meningococcalD', models.DateField(null=True)),
                ('pcv13D', models.DateField(null=True)),
                ('ppsv23D', models.DateField(null=True)),
                ('ipvD', models.DateField(null=True)),
                ('opvD', models.DateField(null=True)),
                ('rotavirusD', models.DateField(null=True)),
                ('rzvD', models.DateField(null=True)),
                ('bcgD', models.DateField(null=True)),
                ('tyfoidFeverD', models.DateField(null=True)),
                ('yellowFeverD', models.DateField(null=True)),
                ('covid19D', models.DateField(null=True)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 518643))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfTB', models.CharField(choices=[('A', 'Active'), ('L', 'Latend')], max_length=1)),
                ('vaccinationForTB', models.BooleanField()),
                ('antibioticConsumption', models.BooleanField()),
                ('numberOfPeopleWithTB', models.IntegerField()),
                ('diagnosticMethodUndertaken', models.CharField(choices=[('S', 'Smear Microscopy'), ('X', 'XPERT/RIF'), ('L', 'Lypoarabinomannan (LAM) Test'), ('T', 'Tuberculin Skin Test (TST)'), ('I', 'Interferon Gamma Release Assays (IGRAs)'), ('O', 'ODYSSEE')], max_length=1)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 517643))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuberculosis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SocialHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAge', models.IntegerField()),
                ('endAge', models.IntegerField()),
                ('smokingYears', models.IntegerField()),
                ('numOfPacksOfCigarettes', models.IntegerField()),
                ('numOfAlcoholGlasses', models.IntegerField()),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 525639))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialhabits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(default='NULL', max_length=200)),
                ('firstName', models.CharField(default='NULL', max_length=200)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='NULL', max_length=1)),
                ('dateOfBirth', models.DateField(default='NULL')),
                ('telephone', models.CharField(default='NULL', max_length=20)),
                ('email', models.CharField(default='NULL', max_length=200)),
                ('familySituation', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('W', 'Widower')], default='NULL', max_length=1)),
                ('nationality', models.CharField(choices=[('AF', 'Afghan'), ('AN', 'Albanian'), ('AL', 'Algerian'), ('AM', 'American'), ('AD', 'Andorran'), ('AO', 'Angolan'), ('AI', 'Anguillan'), ('AB', 'Citizen of Antigua and Barbuda'), ('AG', 'Argentine'), ('AR', 'Armenian'), ('AS', 'Australian'), ('AU', 'Austrian'), ('AZ', 'Azerbaijani'), ('BI', 'Bahamian'), ('BA', 'Bahraini'), ('BC', 'Bangladeshi'), ('BB', 'Barbadian'), ('BS', 'Belarusian'), ('BG', 'Belgian'), ('BI', 'Belizean'), ('BE', 'Beninese'), ('BD', 'Bermudian'), ('BT', 'Bhutanese'), ('BO', 'Bolivian'), ('BH', 'Citizen of Bosnia and Herzegovina'), ('BW', 'Botswanan'), ('BZ', 'Brazilian'), ('BR', 'British'), ('BV', 'British Virgin Islander'), ('BN', 'Bruneian'), ('BL', 'Bulgarian'), ('BK', 'Burkinan'), ('BM', 'Burmese'), ('BU', 'Burundian'), ('CI', 'Cambodian'), ('CM', 'Cameroonian'), ('CN', 'Canadian'), ('CV', 'Cape Verdean'), ('CS', 'Cayman Islander'), ('CF', 'Central African'), ('CA', 'Chadian'), ('CE', 'Chilean'), ('CH', 'Chinese'), ('CL', 'Colombian'), ('CO', 'Comoran'), ('CC', 'Congolese (Congo)'), ('CD', 'Congolese (DRC)'), ('CK', 'Cook Islander'), ('CR', 'Costa Rican'), ('CT', 'Croatian'), ('CU', 'Cuban'), ('CY', 'Cymraes'), ('CB', 'Cymro'), ('CP', 'Cypriot'), ('CZ', 'Czech'), ('DA', 'Danish'), ('DJ', 'Djiboutian'), ('DO', 'Dominican'), ('DR', 'Citizen of the Dominican Republic'), ('DU', 'Dutch'), ('ET', 'East Timorese'), ('EC', 'Ecuadorean'), ('EG', 'Egyptian'), ('EM', 'Emirati'), ('EN', 'English'), ('EQ', 'Equatorial Guinean'), ('ER', 'Erithrean'), ('ES', 'Estonian'), ('EH', 'Ethiopian'), ('FA', 'Faroese'), ('FJ', 'Fijian'), ('FL', 'Filipino'), ('FN', 'Finnish'), ('FR', 'French'), ('GB', 'Gabonese'), ('GA', 'Gambian'), ('GO', 'Georgian'), ('GE', 'German'), ('GH', 'Ghanaian'), ('GI', 'Gibraltarian'), ('GN', 'Greenlandic'), ('GD', 'Grenadian'), ('GZ', 'Guamanian'), ('GT', 'Guatemalan'), ('GC', 'Citizen of Guinea Bissau'), ('GU', 'Guinean'), ('GY', 'Guyanese'), ('HA', 'Haitian'), ('HE', 'Hellenic'), ('HO', 'Honduran'), ('HK', 'Honk Konger'), ('HU', 'Hungarian'), ('IC', 'Icelandic'), ('IN', 'Indian'), ('ID', 'Indonesian'), ('IR', 'Iranian'), ('IQ', 'Iraqi'), ('IH', 'Irish'), ('IS', 'Israeli'), ('IT', 'Italian'), ('IV', 'Ivorian'), ('JM', 'Jamaican'), ('JP', 'Japanese'), ('JO', 'Jordanian'), ('KA', 'Kazakh'), ('KE', 'Kenyan'), ('KT', 'Kittitian'), ('KR', 'Citizen of Kiribati'), ('KO', 'Kosovan'), ('KU', 'Kuwaiti'), ('KY', 'Kyrgyz'), ('LO', 'Lao'), ('LT', 'Latvian'), ('LA', 'Lebanese'), ('LB', 'Liberian'), ('LY', 'Libyan'), ('LC', 'Lichtenstein citizen'), ('LI', 'Lithuanian'), ('LU', 'Luxembourger'), ('MC', 'Macanese'), ('ML', 'Malagasy'), ('MW', 'Malawian'), ('MY', 'Malaysian'), ('MD', 'Maldivian'), ('MF', 'Malian'), ('MJ', 'Maltese'), ('MH', 'Marshallese'), ('MK', 'Martiniquais'), ('MA', 'Mauritanian'), ('MU', 'Mauritian'), ('ME', 'Mexican'), ('MI', 'Micronesian'), ('MO', 'Moldovan'), ('MQ', 'Monegasque'), ('MG', 'Mongolian'), ('MT', 'Montenegrin'), ('MN', 'Montserratian'), ('MR', 'Moroccan'), ('MS', 'Mosotho'), ('MZ', 'Mozambican'), ('NM', 'Namibian'), ('NU', 'Nauruan'), ('NP', 'Nepalese'), ('NZ', 'New Zealander'), ('NC', 'Nicaraguan'), ('NA', 'Nigerian'), ('NE', 'Nigerien'), ('NN', 'Niuean'), ('NK', 'North Korean'), ('ND', 'North Macedonian'), ('NI', 'Northern Irish'), ('NO', 'Norwegian'), ('OM', 'Omani'), ('PK', 'Pakistani'), ('PA', 'Palauan'), ('PS', 'Palestinian'), ('PM', 'Panamanian'), ('PG', 'Papua New Guinean'), ('PY', 'Paraguayan'), ('PE', 'Peruvian'), ('PI', 'Pitcairn Islander'), ('PL', 'Polish'), ('PO', 'Portuguese'), ('PR', 'Prydeinig'), ('PU', 'Puerto Rican'), ('QA', 'Qatari'), ('RO', 'Romanian'), ('RU', 'Russian'), ('RW', 'Rwandan'), ('SV', 'Salvadorian'), ('SM', 'Sammarinese'), ('SA', 'Samoan'), ('ST', 'Sao Tomean'), ('SB', 'Saudi Arabian'), ('SC', 'Scottish'), ('SG', 'Senegalese'), ('SE', 'Serbian'), ('SJ', 'Citizen of Seychelles'), ('SL', 'Sierra Leonean'), ('SN', 'Singaporean'), ('SK', 'Slovak'), ('SO', 'Slovenian'), ('SI', 'Solomon Islander'), ('SM', 'Somali'), ('SF', 'South African'), ('S_', 'South Korean'), ('SS', 'South Sundanese'), ('SP', 'Spanish'), ('S-', 'Sri Lankan'), ('SH', 'St Helenian'), ('SU', 'St Lucian'), ('SQ', 'Stateless'), ('SD', 'Sudanese'), ('SR', 'Surinamese'), ('SZ', 'Swazi'), ('S+', 'Swedish'), ('SW', 'Swiss'), ('SY', 'Syrian'), ('TA', 'Taiwanese'), ('TJ', 'Tajik'), ('TN', 'Tanzanian'), ('TH', 'Thai'), ('TG', 'Togolese'), ('TO', 'Tongan'), ('TR', 'Trinidadian'), ('TS', 'Tristanian'), ('TI', 'Tunisian'), ('TK', 'Turkish'), ('TM', 'Turkmen'), ('TC', 'Turks and Caicos Islander'), ('TV', 'Tuvaluan'), ('UG', 'Ugandan'), ('UK', 'Ukrainian'), ('UR', 'Uruguayan'), ('UZ', 'Uzbek'), ('VT', 'Vatican citizen'), ('VN', 'Citizen of Vanuatu'), ('VE', 'Venezuelan'), ('VS', 'Vietnamese'), ('VI', 'Vincentian'), ('WA', 'Wallisian'), ('WE', 'Welsh'), ('YE', 'Yemeni'), ('ZA', 'Zambian'), ('ZI', 'Zimbabwean')], default='NULL', max_length=2)),
                ('race', models.CharField(choices=[('C', 'Caucasian'), ('Y', 'Yellow'), ('L', 'Latino-American'), ('B', 'Black')], default='NULL', max_length=1)),
                ('language', models.CharField(choices=[('C', 'Mandarin Chinese'), ('E', 'English'), ('H', 'Hindustani'), ('S', 'Spanish'), ('A', 'Arabic'), ('M', 'Malay'), ('R', 'Russian'), ('B', 'Bengali'), ('P', 'Portuguese'), ('F', 'French'), ('G', 'German'), ('J', 'Japanese'), ('I', 'Italian'), ('O', 'Other')], default='NULL', max_length=1)),
                ('occupation', models.CharField(choices=[('B', 'Management, business and financial ocupations'), ('L', 'Professional and related ocupations'), ('S', 'Service ocupations'), ('D', 'Sales and related ocupations'), ('O', 'Officw and administrative support ocupation'), ('F', 'Farming, fishing and forestry ocupations'), ('C', 'Constraction and extractions ocupations'), ('I', 'Installation, maintenance and repair ocupations'), ('P', 'Production ocupations'), ('T', 'Transportation and material moving ocupations'), ('A', 'Armed forces'), ('U', 'Unocupied')], default='NULL', max_length=1)),
                ('education', models.CharField(choices=[('S', 'Primary school graduate'), ('H', 'Hight school graduate'), ('J', 'Junior hight school graduate'), ('T', 'Higher technological education'), ('E', 'Higher education'), ('M', 'Master'), ('P', 'Phd')], default='NULL', max_length=1)),
                ('healthInsurance', models.CharField(choices=[('S', 'State health insurance'), ('P', 'Private health insurance'), ('I', 'State and private health insurance'), ('W', 'Welfare'), ('N', 'None')], default='NULL', max_length=1)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 515623))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaldata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseses', models.CharField(default='NULL', max_length=200, null=True)),
                ('dailyMedication', models.CharField(default='NULL', max_length=200)),
                ('cancerOrTumor', models.BooleanField(default=False)),
                ('bloodTransfusions', models.BooleanField(default=False)),
                ('allergies', models.CharField(default='NULL', max_length=200)),
                ('surgeries', models.CharField(default='NULL', max_length=200)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 521642))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalhistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='GynecologicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAge', models.IntegerField()),
                ('endAge', models.IntegerField()),
                ('numOfChildren', models.IntegerField()),
                ('endometriosis', models.BooleanField()),
                ('polycysticOvarySyndrome', models.BooleanField()),
                ('hormonalContraceptiveTherapy', models.IntegerField()),
                ('hormoneTherapyPregnancy', models.IntegerField()),
                ('notCompletedPregnancies', models.IntegerField()),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 524620))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gynecologicalhistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='DoctorsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('hearing', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('vision', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('respiratoryTract', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('heart', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('chest', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('lungs', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('abdomen', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('myoskeleticalSystem', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('limbs', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('skin', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('nervousSystem', models.CharField(choices=[('E', 'Excelent'), ('M', 'Moderate'), ('C', 'Critical'), ('U', 'Urgent')], default='NULL', max_length=1)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 523640))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorscomments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='CurrentTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 516643))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currenttreatment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default='0')),
                ('weight', models.FloatField(default='0')),
                ('weistline', models.FloatField(default='0')),
                ('bmi', models.FloatField(default='0')),
                ('systolic', models.IntegerField(default='0')),
                ('diastolic', models.IntegerField(default='0')),
                ('pulse', models.IntegerField(default='0')),
                ('respiratoryRythm', models.IntegerField(default='0')),
                ('temperature', models.FloatField(default='0')),
                ('hospital', models.CharField(choices=[], max_length=1)),
                ('dateOfUpdate', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 13, 42, 522641))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicalexamination', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
